version: '3.7'
services:
  order-service:
    image: ${GROUP_ID}/order.service:${SERVICE_VERSION:-latest}
    ports:
      - "8080:8080"
      - "5005:5005"
    user: root
    entrypoint: [ "bash", "rabbitmq-status.sh" ]
    volumes:
      - "./docker-logs:/workspace/order.service/logs"
      - "./rabbitmq-status.sh:/usr/local/bin/rabbitmq-status.sh"
    environment:
      #      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
      - "JAVA_OPTS=-Dapp.clients.scheme=http -Dspring.profiles.active=dev-docker -Dserver.port=8080 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
    networks:
      - ${GLOBAL_NETWORK:-services}
  email-service:
    image: ${GROUP_ID}/email.service:${SERVICE_VERSION:-latest}
    ports:
      - "8888:8888"
      - "5007:5007"
    user: root
    entrypoint: [ "bash", "rabbitmq-status.sh" ]
    volumes:
      - "./docker-logs:/workspace/email.service/logs"
      - "./rabbitmq-status.sh:/usr/local/bin/rabbitmq-status.sh"
    environment:
      #      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
      - "JAVA_OPTS=-Dapp.clients.scheme=http -Dspring.profiles.active=dev-docker -Dserver.port=8081 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -Xms128m -Xmx256m"
    networks:
      - ${GLOBAL_NETWORK:-services}
  stock-service:
    image: ${GROUP_ID}/stock.service:${SERVICE_VERSION:-latest}
    ports:
      - "8081:8081"
      - "5006:5006"
    user: root
    entrypoint: [ "bash", "rabbitmq-status.sh" ]
    volumes:
      - "./docker-logs:/workspace/email.service/logs"
      - "./rabbitmq-status.sh:/usr/local/bin/rabbitmq-status.sh"
    environment:
      #      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
      - "JAVA_OPTS=-Dapp.clients.scheme=http -Dspring.profiles.active=dev-docker -Dserver.port=8888 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007 -Xms128m -Xmx256m"
    networks:
      - ${GLOBAL_NETWORK:-services}